# Generated by Django 3.0.4 on 2020-05-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bar_code',
            new_name='ssn',
        ),
        migrations.RemoveField(
            model_name='books',
            name='qty',
        ),
        migrations.AddField(
            model_name='books',
            name='barcode',
            field=models.BigIntegerField(default=1),
        ),
    ]
