# Generated by Django 3.0.4 on 2020-05-06 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_auto_20200505_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='qty',
        ),
    ]
