# Generated by Django 3.0.4 on 2020-08-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_remove_books_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.AlterModelOptions(
            name='bookissued',
            options={'verbose_name_plural': 'Book Issued'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
    ]
