# Generated by Django 3.0.4 on 2020-04-23 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookIssued',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.BigIntegerField()),
                ('title', models.CharField(max_length=50)),
                ('issue_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=50, unique=True)),
                ('bar_code', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('qty', models.IntegerField(default=1)),
                ('author', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('img', models.ImageField(upload_to='cover')),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='books_pdf')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=255)),
                ('roll_no', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('mob_no', models.BigIntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_no', models.BigIntegerField(unique=True)),
                ('admin', models.BooleanField(default=False)),
                ('student', models.BooleanField(default=False)),
                ('faculty', models.BooleanField(default=False)),
                ('books', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
