# Generated by Django 3.0.4 on 2020-05-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0003_auto_20200505_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissued',
            name='id',
        ),
        migrations.AddField(
            model_name='bookissued',
            name='ssn',
            field=models.BigIntegerField(default=45454545, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
